const CARACTERES = new Map();

CARACTERES.set('A', '.-');
CARACTERES.set('B', '-...');
CARACTERES.set('C', '-.-.');
CARACTERES.set('D', '-..');
CARACTERES.set('E', '.');
CARACTERES.set('F', '..-.');
CARACTERES.set('G', '--.');
CARACTERES.set('H', '....');
CARACTERES.set('I', '..');
CARACTERES.set('J', '.---');
CARACTERES.set('K', '-.-');
CARACTERES.set('L', '.-..');
CARACTERES.set('M', '--');
CARACTERES.set('N', '-.');
CARACTERES.set('O', '---');
CARACTERES.set('P', '.--.');
CARACTERES.set('Q', '--.-');
CARACTERES.set('R', '.-.');
CARACTERES.set('S', '...');
CARACTERES.set('T', '-');
CARACTERES.set('U', '..-');
CARACTERES.set('V', '...-');
CARACTERES.set('W', '.--');
CARACTERES.set('X', '-..-');
CARACTERES.set('Y', '-.--');
CARACTERES.set('Z', '--..');
CARACTERES.set(' ', '/');